### ISSUE TITLE
[Suggestion]: Add "REDACTED FOR PRIVACY" detection

### ISSUE THREAD

**Issue by Starmania** [mboot-github/WhoisDomain#1]
Like NoneStrings for non-existant domain, but get an output and not a None.

So in the case where there is a key but content REDACTED, it's knowable.

**Comment by mboot-github** [comment]
Will have a look we can switch off

https://github.com/mboot-github/WhoisDomain/blob/master/whoisdomain/_2_parse.py#L264

With a extra flag for example

**Comment by Starmania** [comment]
Ok good

Le mer. 24 mai 2023, 17:54, mboot-github ***@***.***> a
écrit :

> Will have a look we can switch off
>
>
> https://github.com/mboot-github/WhoisDomain/blob/master/whoisdomain/_2_parse.py#L264
>
> With a extra flag for example
>

**Comment by Starmania** [comment]
The withRedacted argument is a good compromise, thanks !

**Comment by Starmania** [comment]
Yea... I was seeing the same thing....

**Comment by mboot-github** [comment]
```
#! /usr/bin/env python3

import whoisdomain as whois

domain = "meta.alsace"

d = whois.query(
    domain,
    withRedacted=True,
)

if d:
    print(d.__dict__)
else:
    print(None)```

**Comment by Starmania** [comment]
It's for now a really good job, most of needed feature is now present, and I can finish my work... Thanks you again!
