### ISSUE TITLE
Old version in PYPI

### ISSUE THREAD

**Issue by 07h** [mboot-github/WhoisDomain#12]
Hello. I have a problem

i install via poety
```
% poetry add whoisdomain   
Using version ^1.20230804.2 for whoisdomain

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing whoisdomain (1.20230804.2)

Writing lock file
```

and have the error
```
../Backend/env/lib/python3.11/site-packages/whoisdomain/doWhoisCommand.py", line 162, in _execute_whois_query
    raise WhoisCommandTimeout(f"timeout: query took more then {pc.timeout} seconds")
whoisdomain.exceptions.WhoisCommandTimeout: timeout: query took more then 0.0 seconds
```
but this old version of code, not new

**Comment by mboot-github** [comment]
What query do you run , what domain

**Comment by 07h** [comment]
the problem is elsewhere. there is no line 162 in your repository in
doWhoisCommand.py file. but for some reason, when installing, another
version, the old one

**Comment by mboot-github** [comment]
Poetry uses pypi for install?
I wil add a test in my makefile

**Comment by mboot-github** [comment]
you can find the code in: https://github.com/mboot-github/WhoisDomain/archive/refs/tags/1.20230804.2.tar.gz

**Comment by mboot-github** [comment]
and line 160 is executing a whois command on the cli, why that would trigger during install is the unknown, the install itself should not execute either the whoiscommand that gets installed or execute a query

**Comment by mboot-github** [comment]
all i can think of is "not r"

what says 
which whois
my system fedora38 says: /usr/bin/whois

**Comment by mboot-github** [comment]
and note what is released on pypi is always in the past, 
development continues, 
the proper release code is always downloadable via tags and releases on github

**Comment by mboot-github** [comment]
bug confirmed, there is a issue with the specified timeout if non is provided, hope to have a fix today, yanked the versions on pypi before 20230720

**Comment by mboot-github** [comment]
fixed in the latest pypi: whoisdomain 1.20230807.1

**Comment by mboot-github** [comment]
can we close the issue ?

**Comment by 07h** [comment]
Yes, thank you!
