### ISSUE TITLE
How can i fix FailedParsingWhoisOutput in windows 11

### ISSUE THREAD

**Issue by itkhansunny** [mboot-github/WhoisDomain#2]
I faced this problem in my windows 11 pc, Please tell me how can i fix following problem

![Screenshot_13](https://github.com/mboot-github/WhoisDomain/assets/3222972/f70c201f-0eae-49d4-a46e-b4f5e245a37b)

**Comment by mboot-github** [comment]
First please run with --verbose

**Comment by mboot-github** [comment]
FYI:

* i started my win 11 virtual machine and installed python 3.11.3 from the python website (https://www.python.org/downloads/windows/)
* then installed pythonwhois with pip 
ran whoisdomain -d google.com 
as there was no whois installed i got a error message
* so i installed the sysinternals suite in c:\sysinternalsuite and adapted the path environment to include the c:\sysinternalssuite and verified that i now have the whois command
* on first start of the whois i get some popup to agree 
* then the whoisdomain -d google.com works as expected

what `whois` command did you install on windows, as by default there is no `whois` command on windows.

**Comment by itkhansunny** [comment]
Understand, Please maked as fixed

Thank you

**Comment by itkhansunny** [comment]
Understand, Please maked as fixed

Thank you
