### ISSUE TITLE
Redacted for privacy values

### ISSUE THREAD

**Issue by baderdean** [mboot-github/WhoisDomain#22]
https://github.com/mboot-github/WhoisDomain/blob/5a16aee9eb329b93215a8727466ee63ac4fb343d/whoisdomain/whoisParser.py#L278

Hello, 3 comments on this:
1. great feature, thanks a lot @mboot-github 
2. In Python, we'll write ```with_redacted``` instead of withRedacted and you test it ```if not with_redacted``` or ```if with_redacted``` without testing ```is False```. pascalCase and CamelCase are for class objects usually https://peps.python.org/pep-0008/#function-and-variable-names , that's why I highly recommend implementing a linting tool as part of the CI/CD of this repo (e.g black, ruff in a pre-commit hook)
3. Identified values for redacted Whois:

```
REDACTED_TEXT = (
    "<data not disclosed>",
    "Contact Privacy Inc. Customer",
    "Data Protected",
    "Domain Privacy Trustee SA",
    "Domains By Proxy, LLC",
    'Data Privacy Protected',
    'Domain Privacy Service FBO Registrant',
    'Domain Privacy Service FBO Registrant.',
    'Domain Privacy Trustee',
    "Domain Protection Services",
    # too common word, should be removed
    # "hidden",
    "Identity Protect Limited",
    "Identity Protection Service",
    'Jewella Privacy LLC Privacy ID#',
    'MyPrivacy.net',
    "NameBrightPrivacy.com",
    "NO FORMAT!",
    # too common word, should be removed
    #"None",
    "Not Disclosed",
    "Not shown, please visit www.dnsbelgium.be for webbased whois.",
    "[PRIVATE]",
    'Privacy Protection',
    'PrivacyGuardian.org llc',
    "Privacy service provided by Withheld for Privacy ehf",
    "REDACTED FOR PRIVACY",
    'Redacted for GDPR privacy',
    "Redacted for Privacy",
    "Redacted for Privacy Purposes",
    "Statutory Masking Enabled",
    'See PrivacyGuardian.org',
    'Super domains privacy',
    'Whois Privacy',
    'Whois Privacy Protection Foundation',
    'Whois Privacy Protection Service',
    'Whois Privacy Protection Service by VALUE-DOMAIN',
    'Whois Privacy Protection Service by onamae.com',
    "Whois Privacy Service",
    "Whoisprotection.cc",
    "Withheld for Privacy Purposes",
)
```
and the test itself will become
```
            if not self.pc.with_redacted:
                # these lines contribute nothing so ignore
                if any(redacted in line for redacted in REDACTED_TEXT):  
                    continue
  ```

**Comment by mboot-github** [comment]
black is part of the makefile (bin/reformat-code.sh)
i currently suppress some codes for pylama, later we can see if we relax
that

currently im not so concerned about total python correctness,
this is anyway inherited from code with a long history,
it took some effort to make it more modern
tools liek black, pylama and mypy already helped significantly to cleanup a
lot of mess

**Comment by mboot-github** [comment]
ignore strings are in the latest release 1.20230913.1
