### ISSUE TITLE
generic WhoisException

### ISSUE THREAD

**Issue by baderdean** [mboot-github/WhoisDomain#23]
https://github.com/mboot-github/WhoisDomain/blob/5a16aee9eb329b93215a8727466ee63ac4fb343d/whoisdomain/exceptions.py#L1

Could we have a generic WhoisException please? It would be helpful instead of having a length except with the whole exception in many case where I don't care about the Exception in itself (I logged it but that's all).

You could have a look at how it's done here for instance: https://docs.python-requests.org/en/latest/_modules/requests/exceptions/

**Comment by mboot-github** [comment]
you mean to subclass all current exceptions from a generic one , yes that
should be easy to implement

alternatively you could use simplistic=True

  "simplistic": {
    "type": "bool",
    "default": false,
    "optional": true,
    "help": "when simplistic is true we return null for most exceptions and
dont pass info why we have no data."
  },

**Comment by mboot-github** [comment]
added "WhoisException" in https://github.com/mboot-github/WhoisDomain/blob/master/whoisdomain/exceptions.py

**Comment by mboot-github** [comment]
is now in the latest release 1.20230913.1
