### ISSUE TITLE
Whois doesn't run

### ISSUE THREAD

**Issue by PhuyalGaurav** [mboot-github/WhoisDomain#27]
## [WinError 2] on running the library
when i try to run whoisdomain in anyway i get a `FileNotFoundError: [WinError 2] The system cannot find the file specified` error

## To Reproduce
```
import whoisdomain
d = whoisdomain.query('google.com')
print(d.__dict__)
```
Running even this example code gives me that error

## Expected behavior
Running the script gives me this error

## Screenshots
![image](https://github.com/mboot-github/WhoisDomain/assets/130540346/3c5ff7a9-263a-4a58-b5e9-a133f7696f16)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser : none
 - Version : python 3.12,3.11 || whois [1.20131115.1](https://github.com/mboot-github/WhoisDomain/releases/tag/1.20231115.1)

**Comment by mboot-github** [comment]
You did install the whois cli ?

**Comment by PhuyalGaurav** [comment]
sorry i forgot to close this. Yea it ran after installing who is cli. for anyone else going through this problem you can install whois cli from [whoiscli](https://learn.microsoft.com/en-us/sysinternals/downloads/whois)

**Comment by mboot-github** [comment]
Super, thanks
