### ISSUE TITLE
Can I do unlimited requests?

### ISSUE THREAD

**Issue by Martijn3161** [mboot-github/WhoisDomain#28]
I have a question. Most of the WhoIs python packages require a WhoIs API key. This one doesn't. Can I do unlimited requests and if so is this package just scraping the data from some website to check if it is available?

**Comment by mboot-github** [comment]
This package uses the native Linux/Mac/windows command line "whois" to do it's work. 
No keys required.
But note that a individual whois server for a toplevel domain may have limitations of max amount of requests per second.

**Comment by Martijn3161** [comment]
> This package uses the native Linux/Mac/windows command line "whois" to do it's work. No keys required. But note that a individual whois server for a toplevel domain may have limitations of max amount of requests per second.

So then I get a error if I reached the limit right?

**Comment by mboot-github** [comment]
Yes

**Comment by Martijn3161** [comment]
>>> Last update of whois database: 2024-01-15T20:38:27Z <<<



NOTICE: The expiration date displayed in this record is the date the

registrar's sponsorship of the domain name registration in the registry is

currently set to expire. This date does not necessarily reflect the expiration

date of the domain name registrant's agreement with the sponsoring

registrar.  Users may consult the sponsoring registrar's Whois database to

view the registrar's reported date of expiration for this registration.



TERMS OF USE: You are not authorized to access or query our Whois

database through the use of electronic processes that are high-volume and

automated except as reasonably necessary to register domain names or

modify existing registrations; the Data in VeriSign Global Registry

Services' ("VeriSign") Whois database is provided by VeriSign for

information purposes only, and to assist persons in obtaining information

about or related to a domain name registration record. VeriSign does not

guarantee its accuracy. By submitting a Whois query, you agree to abide

by the following terms of use: You agree that you may use this Data only

for lawful purposes and that under no circumstances will you use this Data

to: (1) allow, enable, or otherwise support the transmission of mass

unsolicited, commercial advertising or solicitations via e-mail, telephone,

or facsimile; or (2) enable high volume, automated, electronic processes

that apply to VeriSign (or its computer systems). The compilation,

repackaging, dissemination or other use of this Data is expressly

prohibited without the prior written consent of VeriSign. You agree not to

use electronic processes that are automated and high-volume to access or

query the Whois database except as reasonably necessary to register

domain names or modify existing registrations. VeriSign reserves the right

to restrict your access to the Whois database in its sole discretion to ensure

operational stability.  VeriSign may restrict or terminate your access to the

Whois database for failure to abide by these terms of use. VeriSign

reserves the right to modify these terms at any time.



The Registry database contains ONLY .COM, .NET, .EDU domains and

Registrars.

**Comment by Martijn3161** [comment]
TERMS OF USE: You are not authorized to access or query our Whois

database through the use of electronic processes that are high-volume


I cannot use this in python it says in the terms of use

**Comment by mboot-github** [comment]
i usually use extensive caching so i dont query records that i already know and that are unlikely to have changed ( based on expiry date)

but yes many individual whois servers have their own limits set and their own rules.

whoisdomain is just a parser for the whois cli data it is not a service separate from cli whois

i will close the issue, if there are no open questions
