### ISSUE TITLE
Missing ccTLD Second-Level Support: UK

### ISSUE THREAD

**Issue by ghost** [mboot-github/WhoisDomain#29]
`me.uk` isn't in `validTlds()`.

List of all `.uk` 2nd-level domains can be found here: https://en.wikipedia.org/wiki/.uk#Second-level_domains

**Comment by mboot-github** [comment]
We use https://github.com/publicsuffix/list which is a static list.
( https://publicsuffix.org/list/public_suffix_list.dat )
I will see if we can update.

See also docs/Updates:

1.20230913.1

   - if you have installed tld (pip install tld) you can enable
   withPublicSuffix=True to process untill you reach the pseudo tld.
   - the public_suffix info is added if available (and if requested)
   - example case is: ./test2.py -d www.dublin.airport.aero
    --withPublicSuffix

**Comment by mboot-github** [comment]
do you have  example to test with ?

**Comment by mboot-github** [comment]
example with tld used:
```
#! /usr/bin/env python3

import whoisdomain
import tld

domain= "xxx.me.uk"

d = whoisdomain.query(domain=domain, withPublicSuffix=True)
print(d.__dict__)
```
output:
```
python3 me.py `without withPublicSuffix=True`
{'name': 'xxx.me.uk', 'tld': 'uk', 'registrar': 'Tucows Inc t/a Tucows [Tag = TUCOWS-CA]', 'registrant_country': '', 'creation_date': datetime.datetime(2002, 1, 14, 0, 0), 'expiration_date': datetime.datetime(2025, 1, 14, 0, 0), 'last_updated': datetime.datetime(2024, 1, 13, 0, 0), 'dnssec': False, 'status': 'Registered until expiry date.', 'statuses': ['Registered until expiry date.'], 'name_servers': ['ns1.aabcit.com', 'ns2.aabcit.com'], 'registrant': '', 'emails': []}

python3 me.py with `withPublicSuffix=True`
{'name': 'xxx.me.uk', 'tld': 'uk', 'public_suffix': 'me.uk', 'registrar': 'Tucows Inc t/a Tucows [Tag = TUCOWS-CA]', 'registrant_country': '', 'creation_date': datetime.datetime(2002, 1, 14, 0, 0), 'expiration_date': datetime.datetime(2025, 1, 14, 0, 0), 'last_updated': datetime.datetime(2024, 1, 13, 0, 0), 'dnssec': False, 'status': 'Registered until expiry date.', 'statuses': ['Registered until expiry date.'], 'name_servers': ['ns1.aabcit.com', 'ns2.aabcit.com'], 'registrant': '', 'emails': []}

```

**Comment by mboot-github** [comment]
the use of tld is actually the more correct one as the real tld is `uk` and not `me.tld`.

**Comment by mboot-github** [comment]
ok investigating: 

as i need a example with each tld and pseudo tls there are some that cannot be added as either i have no example or there does not seem to be a whois server for the second level (police.uk, nhs.uk for example) and the default whois.nic.uk does not work for those.

xxx.me.uk works as example so me.uk is added in the current working tree
as is gov.uk, 

plc.uk and ltd.uk would be nice to have but again i would need a example to test as the format of many second level is diffrent from standard uk , ac,uk or co.uk.

**Comment by case-fastly** [comment]
Fwiw, `me.uk` is the "registered domain" here, not the `www` variant.

**Comment by mboot-github** [comment]
Yes as part of the original implementation we strip www as it is not a
domain.

**Comment by mboot-github** [comment]
We can naturally add a sitch not to treat www as a host, for special cases

**Comment by mboot-github** [comment]
example

in the latest code:

```
WhoisDomain]$ ./test2.py -d www.me.uk --withNoIgnoreWww

test domain: <<<<<<<<<< www.me.uk >>>>>>>>>>>>>>>>>>>>
name               str               'www.me.uk'
tld                str               'me.uk'
registrar          str               'Andrews &amp; Arnold Limited [Tag =
AAISP]'
registrant_country str               ''
creation_date      datetime.datetime 2002-01-14 00:00:00
expiration_date    datetime.datetime 2026-01-18 00:00:00
last_updated       datetime.datetime 2024-01-17 00:00:00
dnssec             bool              False
status             str               'Registered until expiry date.'
statuses           list              ['Registered until expiry date.']
name_servers       list              ['primary-dns.co.uk', '
secondary-dns.co.uk']
owner              str               ''
registrant         str               ''
emails             list              []

WhoisDomain]$ ./test2.py -d www.me.uk

test domain: <<<<<<<<<< www.me.uk >>>>>>>>>>>>>>>>>>>>
None

 {'Try': []}
```

**Comment by mboot-github** [comment]
my error, i forgot passing the additional argument when using query(), it
if fixed in the latest commit

**Comment by mboot-github** [comment]
a new pypi version has been released including this

https://pypi.org/project/whoisdomain/

**Comment by mboot-github** [comment]
i expect we can close this now if there are no additional issues

**Comment by mboot-github** [comment]
with withPublicSuffix=True me.uk is treated as a toplevel domain so no information is retiteved, try with out that option or use withPublicSuffix=False

**Comment by mboot-github** [comment]
Actually now that we added me.uk also to the old regexp table we would have
to add a dedicated switch to show whois data of a TLD or pseudo TLD if that
is needed, normally the module dies not show TLD domain info.
