### ISSUE TITLE
Using the library only for parsing

### ISSUE THREAD

**Issue by guidiandrea** [mboot-github/WhoisDomain#9]
Hello @maarten-boot, thanks for continuing with the development of this library.

With a previous version, I was able to parse a raw WHOIS string without necessarily passing through the `query` function. Is it still the case now?

**Comment by mboot-github** [comment]
https://github.com/mboot-github/WhoisDomain/blob/master/whoisdomain/_1_query.py#L48

You probabely mean the test function i use to compare exiting file data
The library code is identical currently for whois an whoisdomain so i would
e pect you can still use the same logic

How are you using it currently ?

**Comment by mboot-github** [comment]
it my suggestion clear ?
can we close this issue or would you prefer more feedback ?

**Comment by mboot-github** [comment]
i will close the issue for now, feel free to re-open if needed
